### ISSUE TITLE
日報が1つでも登録されているプロジェクトに関しては、プロジェクト削除できないようにする。

### ISSUE THREAD

**Issue by rswisteria** [xtone/daily-report#100]
「管理画面」→「プロジェクト管理」→プロジェクトを選択 (`/projects/:id`) のプロジェクト詳細ページで、プロジェクトの削除ができてしまうが、これを行うと集計や日報の表示が正しく行えなくなる問題がある。そもそも消していいデータではない。

削除ボタンはプロジェクト作成時に誤って作成した場合のために用意してあるので、1つでも日報が入力されているものについては削除ボタンを表示しないように修正する。

**Comment by sktaz** [comment]
#102 で対応済みなのでclose
