### ISSUE TITLE
ユーザーログイン機能実装

### ISSUE THREAD

**Issue by k-kibi** [xtone/daily-report#6]
#4 に関連、管理アカウントとはできることが違うので、権限を分けたい。

なんか良い方法あったら教えてください。

**Comment by rswisteria** [comment]
deviseだとrollの機能があった気がする

**Comment by k-kibi** [comment]
[RailsApps/rails-devise-roles](https://github.com/RailsApps/rails-devise-roles) に、Deviseを使った実装サンプルがありました。
usersテーブルにroleってenumなカラムが追加されてるというシンプルな感じのものですが
こんなのでもいいですかね

**Comment by k-kibi** [comment]
[Pundit](https://github.com/elabs/pundit) を利用して、ユーザーの権限を３種類（管理者・総務・ディレクター）用意しました。
もしかすると必要ないものもあるかもしれませんが。
