### ISSUE TITLE
入力画面で日付が消える

### ISSUE THREAD

**Issue by knktkc** [xtone/daily-report#63]
## 概要

以下のような画面になります。
![2018-02-27 18 39 47](https://user-images.githubusercontent.com/18133903/36721243-a9954f1a-1bed-11e8-9ef5-5e8fcb6ba38c.png)

## 問題の原因

consoleを見ると以下のコードでエラーが出ているようです。
https://github.com/xtone/daily-report/blob/80edaca01ab384616667db363c2dc4eecbf01e4d/app/javascript/packs/reports.jsx#L28

```
POST http://daily-report.xtone.co.jp/settings/projects.json 404 (Not Found)
```

### 発生方法

1. ログインする
2. 日報を入力する
3. 別の月を選択する

100%発生します。

## 補足

ブラウザをリロードすると選択した月が表示されるので、とくに問題はないのですが、念のため報告です。

**Comment by k-kibi** [comment]
日報データをPOSTしたあと、画面上部のナビゲーションをクリックすると、
GET ではなく POST でリクエストされる不具合があるようです。

**Comment by k-kibi** [comment]
修正して本番適用済み
